name: Release Actions
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          semantic_version: 15.13.28
          branch: 
            'main'
        env:
          TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
